### ISSUE TITLE
Using two MPU9250s at the same time

### ISSUE THREAD

**Issue by Daniel-t** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#26]
Has anyone managed to use this library (with modification) to support using more than one 9250 at a time?

I've made some basic changes to pass the I2C address through in the begin function, however it gets overwritten by subsequent calls from a different object instance.

**Comment by santaimpersonator** [comment]
As mentioned in the [datasheet](https://cdn.sparkfun.com/assets/learn_tutorials/5/5/0/MPU9250REV1.0.pdf), you need to configure the I2C address through the hardware. Otherwise, you will need to terminate your I2C connection and access your secondary device (see videos below).

- https://www.youtube.com/watch?v=j6B47reye80
- https://www.youtube.com/watch?v=zzieeHmFSis
